W 012 3
wojciechwelfle/plortal pull request #53
Opened 2024-05-13 18:37 UTC by WOJTASK1

This is beta version of the navigation bar. For now, all of the requirements set at the task are fullfiled.

2024-05-13 23:21 UTC, MartynaSzymanskaGitHub commented on frontend/src/components/navbar/Navbar.css
change look of the navbar to more figma style

2024-05-13 23:22 UTC, MartynaSzymanskaGitHub commented on frontend/src/components/navbar/Navbar.jsx
code is duplicated and can be shortened . Needs refactoring

2024-05-13 23:23 UTC, MartynaSzymanskaGitHub requested changes
needs to change apperance of navbar
and file conflicts must be resolved

2024-05-15 08:20 UTC, closed without merging

2024-05-15 08:20 UTC, WOJTASK1 commented
outdated.