W 012 3
wojciechwelfle/plortal pull request #65
Opened 2024-05-19 14:30 UTC by WOJTASK1

2024-05-19 21:25 UTC, wojciechwelfle requested changes
format all files and delete comments

2024-05-19 21:25 UTC, wojciechwelfle commented on frontend/src/components/navbar/Navbar.css
> +    background-color: var(--main-color);
delete 38 line

2024-05-20 08:30 UTC, WOJTASK1 commented on frontend/src/components/navbar/Navbar.css
> +    background-color: var(--main-color);
Already done!

2024-05-20 10:21 UTC, wojciechwelfle approved these changes
lgtm

2024-05-20 10:22 UTC, merged