W 038
wojciechwelfle/plortal pull request #98
Opened 2024-06-03 18:36 UTC by MartynaSzymanskaGitHub

refactoring Theme and font Size code

2024-06-03 18:40 UTC, wojciechwelfle requested changes

2024-06-03 18:40 UTC, wojciechwelfle commented on frontend/src/components/facility/ThemeContext.jsx
> +
move context to new folder

2024-06-03 18:40 UTC, wojciechwelfle commented on frontend/src/pages/AdminPanelPage.jsx
> +            <ThemeProvider>
try use ThemeProvider in Rooting component

2024-06-03 18:52 UTC, MartynaSzymanskaGitHub commented
changed files

2024-06-06 22:15 UTC, MartynaSzymanskaGitHub commented
Fix text position

2024-06-07 14:09 UTC, wojciechwelfle approved these changes
lgtm

2024-06-07 14:09 UTC, merged