W-065
wojciechwelfle/plortal pull request #99
Opened 2024-06-05 20:19 UTC by szymon-muszynski

Added option to store basic and additional info on user's profile, connected to database.
Added 2 modes for each textbox - edit, read only mode, and save, where writing is allowed.

2024-06-06 21:05 UTC, WOJTASK1 commented
After changing view to another subpage and coming back to user profile, previously inserted avatar picture disappears. Please check this case.

2024-06-07 14:14 UTC, wojciechwelfle requested changes
refactor todo

2024-06-07 14:14 UTC, wojciechwelfle commented on backend/plortal/src/main/java/com/plortal/plortal/model/entity/User.java
> +    @Column(name = "additionalInfo")
add length = 250

2024-06-07 14:14 UTC, wojciechwelfle commented on backend/plortal/src/main/java/com/plortal/plortal/model/entity/User.java
> +    private String basicInfo;
add length = 250

2024-06-07 14:14 UTC, wojciechwelfle commented on backend/plortal/src/main/java/com/plortal/plortal/controller/UserController.java
> +        try {
move methods to UserInfoController

2024-06-07 14:14 UTC, wojciechwelfle commented on backend/plortal/src/main/java/com/plortal/plortal/service/UserService.java
> +    String getBasicInfo(Long userId);
move to UserInfoService

2024-06-07 14:14 UTC, wojciechwelfle commented on backend/plortal/src/main/java/com/plortal/plortal/service/impl/UserServiceImpl.java
> +    public void updateBasicInfo(Long userId, String basicInfo) {
move to UserInfoServiceImpl

2024-06-10 08:24 UTC, wojciechwelfle approved these changes
lgtm

2024-06-10 08:24 UTC, merged